### ISSUE TITLE
micropython 

### ISSUE THREAD

**Issue by riker65** [karioja/vedirect#12]
Hi,
wondering why this is error occurs, how to solve?

pi@pi3solar:/opt/vedirect/examples$ python3 vedirect_mqtt.py
Traceback (most recent call last):
  File "/opt/vedirect/examples/vedirect_mqtt.py", line 6, in <module>
    from vedirect import Vedirect
  File "/home/pi/.local/lib/python3.9/site-packages/vedirect/__init__.py", line 2, in <module>
    from .vedirect_asyncio import VEDirectAsyncio
  File "/home/pi/.local/lib/python3.9/site-packages/vedirect/vedirect_asyncio.py", line 5, in <module>
    raise NotImplementedError("This is only for Micropython")
NotImplementedError: This is only for Micropython

**Comment by mano8** [comment]
It looks like you are using another micropython fork of this package. Not the original. You can try to install it again or use another fork, depending on the version of python used. Here it looks like you are trying to run Micropython code on a Python interpreter.
